#!/bin/bash

ATFILE_URL=$1
AWS_ACCESS_KEY_ID="AKIAUSUQAVLTX4LXGZUQ"
AWS_SECRET_ACCESS_KEY="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"
GAME_UUID=$2

echo "GAME_UUID = ${GAME_UUID}"

docker run --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} mattfeng/batch_leiserchess ${ATFILE_URL} ${GAME_UUID}
